spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://120.26.217.161:3306/eva?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: suitaba0
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  file:
    name: mylogs.log
    path: /Users/chenjiahan/Desktop/log
